### ISSUE TITLE
document is not available on node.js

### ISSUE THREAD

**Issue by bitinn** [crysalead-js/dom-element-css#1]
https://github.com/crysalead-js/dom-element-css/blob/master/index.js#L2

`dom-layer` depends on `dom-element-css` but this line assumes `document` is also available in node.js global (for server-side rendering)?

**Comment by jails** [comment]
Ah fair enough !
I'll change it to:

``` js
hasRemovePropertyInStyle = typeof document !== "undefined" && "removeProperty" in document.createElement("a").style
```

**Comment by jails** [comment]
Fixed in https://github.com/crysalead-js/dom-element-css/commit/3799e433b0c673e2d5b89543d07756d30f703a07
